title:              90wish
email:              meisho0325@protonmail.com
description:        세상을 새로 쓸 칼끝
author:             메이쇼
baseurl:            #
url:                "https://meisho0325.github.io"

# Social Profiles
twitter_username:   meisho0325
github_username:    meisho0325
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
